### PR TITLE
fix: cap max ingestion batch size

### LINKED ISSUE #70: default batch size fails for tables with many columns
driver sets 1000 as default batch size during bulk ingest. prepared statement with batchSize x numCols placeholders is always prepared regardless of number of rows in the dataset. For tables with many columns (>65) max number of placeholders is reached.

### PR DESCRIPTION
**Pull request by tokoko**
## What's Changed

Calculates maxBatchSize taking into account max placeholder limit and number of columns and caps default or user-provided config.

Closes #70.

### CODE REVIEW

File: go/mysql_test.go [hunk 1]
```diff
@@ -669,6 +669,63 @@ func (s *MySQLTestSuite) TearDownSuite() {
...
+		}
+	}
+	batch := batchbldr.NewRecordBatch()
+	defer batch.Release()
+
+	// Ingest — this would fail before the fix because
+	// 1000 (default batch size) * 100 columns = 100,000 placeholders > 65,535 limit
+	stmt, err := s.cnxn.NewStatement()
+	s.Require().NoError(err)
+	defer s.NoError(stmt.Close())
```
Comment (Mandukhai-Alimaa) [inline go/mysql_test.go]:
```suggestion
	defer func() { s.NoError(stmt.Close()) }()
```

Comment (tokoko) [reply go/mysql_test.go]: got it, thanks
